### ISSUE TITLE
Can't override base fonts

### ISSUE THREAD

**Issue by jbasdf** [mjonuschat/bootstrap-sass-rails#16]
I've tried defining my own fonts for $sansFontFamily but my overrides are ignored.

I've found that in order for the base font to be set I have to add this to my overrides file:
$sansFontFamily:        "Nunito", "Helvetica Neue", Helvetica, Arial, sans-serif;
$baseFontFamily:        $sansFontFamily;

I'm not clear why I have to override $baseFontFamily as well. Shouldn't it pick up $sansFontFamily?

Even with those overrides the form elements are still using the $sansFontFamily defined in the gem. Somehow the call to @include font-sans-serif in the code below is pulling up the fonts from the gem.

// Set font for forms
label,
input,
button,
select,
textarea {
  @include font-shorthand($baseFontSize,normal,$baseLineHeight); // Set size, weight, line-height here
}
input,
button,
select,
textarea {
  // TODO: MOJ - check baseFontFamily
  @include font-sans-serif($baseFontSize,normal,$baseLineHeight); // And only set font-family here for those that need it (note the missing label element)
}

Not sure if it helps but here's the output from _forms.scss:

/\* line 50, ../../../../.rvm/gems/ruby-1.9.3-p0@opentapestry/gems/bootstrap-sass-rails-2.0.2.2/vendor/assets/stylesheets/twitter/bootstrap/_forms.scss */
input,
button,
select,
textarea {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 13px;
  font-weight: normal;
  line-height: 18px;
}

**Comment by mjonuschat** [comment]
The forms should now inherit fonts in the same way they do with the original less version.

**Comment by jbasdf** [comment]
Just tested and it works great. Thanks!
