### ISSUE TITLE
$placeholderText is ignored in _form.scss

### ISSUE THREAD

**Issue by jbasdf** [mjonuschat/bootstrap-sass-rails#17]
There is an entry for the placeHolderText in _variables.scss:

// Input placeholder text color
// -------------------------
$placeholderText:       $grayLight !default;

However, in _forms.scss the value is hard coded to $grayLight:

// Placeholder text gets special styles; can't be bundled together though for some reason
@include placeholder($grayLight);

**Comment by mjonuschat** [comment]
Hi,

this is the way it currently is handled in Twitter Bootstrap - https://github.com/twitter/bootstrap/blob/master/less/forms.less#L346

I try not to deviate from the original to keep merging in the next version as easy as possible. I would suggestusing the placeholder mixin to override the styles/color as you need them.
