### ISSUE TITLE
Upgrade to Bootstrap 2.1.0

### ISSUE THREAD

**Issue by mjonuschat** [mjonuschat/bootstrap-sass-rails#24]
Bootstrap 2.1 has been released - upgrade necessary.

**Comment by kylewest** [comment]
thanks for maintaining this!

**Comment by mjonuschat** [comment]
You're welcome. I've published a 2.1.0.0pre1 this morning - any feedback regardings bugs is welcome!

**Comment by kylewest** [comment]
I just upgraded to it. I'll let you know if I see anything, bundler is taking its sweet time. :)

Kyle

**Comment by kylewest** [comment]
BTW, you should try to get this added to the [bootstrap wiki](https://github.com/twitter/bootstrap/wiki/Forks%2C-Plugins%2C-and-Packages). I was googling for a while before I found a maintained sass package.

**Comment by tarellel** [comment]
Great work, you got this out and released a lot faster than I thought it would. I checked out and the LESS version and YUCK!!! So I'm happy I can stick with my beloved SASS

**Comment by mjonuschat** [comment]
Just to let you know, I've published 2.1.0.0pre2 (with only minor fixes) on Rubygems. If nothing major crops up the next few days I'll be releasing the final 2.1.0.0 on Sunday.

**Comment by ryanlindsey** [comment]
Excellent, really appreciate your work maintaining this project.

**Comment by mjonuschat** [comment]
Thanks for your appreciation! 2.1.0.0 has just been published!
