### ISSUE TITLE
File to import not found or unreadable: bootstrap/variables

### ISSUE THREAD

**Issue by jwaldrip** [mjonuschat/bootstrap-sass-rails#28]
I get this error:

File to import not found or unreadable: bootstrap/variables

my application.css.scss looks like this:

@import "twitter/bootstrap";

**Comment by ryanlindsey** [comment]
You might want to break the import statement out into another file and keep your application.css as a manifest.

**Comment by mjonuschat** [comment]
Are you using Compass/compass-rails? According to issue #25 you need to enable relative assets in your compass-rails config in hat case.
