### ISSUE TITLE
bootstrap-sass-rails seems to break compass

### ISSUE THREAD

**Issue by aaronjensen** [mjonuschat/bootstrap-sass-rails#3]
I can't seem to figure out why, but it appears that it can't import anything else in other gem vendor dirs. I'm still looking into it, but figured I'd open the issue in case you knew.

`@import compass`

`File to import not found or unreadable: compass.`

```
sass (3.1.12) lib/sass/tree/import_node.rb:64:in `rescue in import'
sass (3.1.12) lib/sass/tree/import_node.rb:42:in `import'
sass (3.1.12) lib/sass/tree/import_node.rb:25:in `imported_file'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:149:in `rescue in visit_import'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:154:in `visit_import'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:39:in `with_environment'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:26:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `block in visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:47:in `visit_root'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:7:in `visit'
sass (3.1.12) lib/sass/tree/root_node.rb:20:in `render'
sass (3.1.12) lib/sass/engine.rb:300:in `_render'
sass (3.1.12) lib/sass/engine.rb:247:in `render'
sass-rails (3.2.3) lib/sass/rails/template_handlers.rb:106:in `evaluate'
tilt (1.3.3) lib/tilt/template.rb:76:in `render'
sprockets (2.1.2) lib/sprockets/context.rb:177:in `block in evaluate'
sprockets (2.1.2) lib/sprockets/context.rb:174:in `each'
sprockets (2.1.2) lib/sprockets/context.rb:174:in `evaluate'
sprockets (2.1.2) lib/sprockets/processed_asset.rb:12:in `initialize'
sprockets (2.1.2) lib/sprockets/base.rb:241:in `new'
sprockets (2.1.2) lib/sprockets/base.rb:241:in `block in build_asset'
sprockets (2.1.2) lib/sprockets/base.rb:262:in `circular_call_protection'
sprockets (2.1.2) lib/sprockets/base.rb:240:in `build_asset'
sprockets (2.1.2) lib/sprockets/index.rb:89:in `block in build_asset'
sprockets (2.1.2) lib/sprockets/caching.rb:19:in `cache_asset'
sprockets (2.1.2) lib/sprockets/index.rb:88:in `build_asset'
sprockets (2.1.2) lib/sprockets/base.rb:163:in `find_asset'
sprockets (2.1.2) lib/sprockets/index.rb:56:in `find_asset'
sprockets (2.1.2) lib/sprockets/bundled_asset.rb:38:in `init_with'
sprockets (2.1.2) lib/sprockets/asset.rb:24:in `from_hash'
sprockets (2.1.2) lib/sprockets/caching.rb:15:in `cache_asset'
sprockets (2.1.2) lib/sprockets/index.rb:88:in `build_asset'
sprockets (2.1.2) lib/sprockets/base.rb:163:in `find_asset'
sprockets (2.1.2) lib/sprockets/index.rb:56:in `find_asset'
sprockets (2.1.2) lib/sprockets/environment.rb:74:in `find_asset'
sprockets (2.1.2) lib/sprockets/base.rb:171:in `[]'
```

**Comment by aaronjensen** [comment]
Looks like there's some complexity to getting compass to work... and even more so to get it to work with rails. https://github.com/thomas-mcdonald/bootstrap-sass is working on it at the moment.

**Comment by mjonuschat** [comment]
Hmmm, I can't really reproduce the problem or the complexity. I just created a simple rails application and it worked instantly.

I uploaded it to github so you can give it a spin: https://github.com/yabawock/bootstrap-compass-test

Please report back wether it works for you or what I need to do to reproduce the bug.

**Comment by aaronjensen** [comment]
Well, it looks like my problem went away when I used compass-rails instead of just compass. Didn't know that was what we were supposed to use now. Oops. Thanks :)

**Comment by asharma-ror** [comment]
I am trying to upgrade my rails to 3.2.0 while I run following command
bundle exec rake assets:precompile RAILS_ENV=development RAILS_GROUPS=assets --trace

I get the following error:

File to import not found or unreadable: blueprint.sass.
Load paths:
  Sass::Rails::Importer(/home/ashish/work/ashish/app/assets/stylesheets/ie.sass)
  /home/ashish/work/ashish/app/assets/stylesheets
  /usr/local/rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.1/frameworks/blueprint/stylesheets
  /usr/local/rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.1/frameworks/compass/stylesheets
  /usr/local/rvm/gems/ruby-1.9.3-p194/bundler/gems/compass-twitter-bootstrap-be734a5be9fb/stylesheets
  Compass::SpriteImporter
  (in /home/ashish/work/ashish/app/assets/stylesheets/ie.sass)
/home/ashish/work/ashish/app/assets/stylesheets/ie.sass:1
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/import_node.rb:64:in `rescue in import'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/import_node.rb:42:in`import'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/import_node.rb:25:in `imported_file'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:149:in`rescue in visit_import'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:154:in `visit_import'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`block in visit_children'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`visit_children'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in`with_environment'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`block in visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:7:in`visit'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/tree/root_node.rb:20:in `render'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/engine.rb:299:in`_render'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.17/lib/sass/engine.rb:246:in `render'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sass-rails-3.2.5/lib/sass/rails/template_handlers.rb:106:in`evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/context.rb:177:in`block in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/context.rb:174:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/context.rb:174:in`evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:241:in`new'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:241:in `block in build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:262:in`circular_call_protection'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:240:in `build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:89:in`block in build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/caching.rb:19:in `cache_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:88:in`build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:163:in `find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:56:in`find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/processed_asset.rb:106:in `block in build_required_assets'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/processed_asset.rb:100:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/processed_asset.rb:100:in `build_required_assets'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/processed_asset.rb:16:in`initialize'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:241:in `new'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:241:in`block in build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:262:in `circular_call_protection'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:240:in`build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:89:in `block in build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/caching.rb:19:in`cache_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:88:in `build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:163:in`find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:56:in `find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/bundled_asset.rb:16:in`initialize'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:244:in `new'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:244:in`build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:89:in `block in build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/caching.rb:19:in`cache_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:88:in `build_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:163:in`find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/index.rb:56:in `find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/environment.rb:74:in`find_asset'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/static_compiler.rb:20:in `block in compile'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:212:in`block in each_logical_path'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:200:in `block (2 levels) in each_file'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:190:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:190:in `each_entry'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:198:in`block in each_file'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:197:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:197:in`each_file'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.1.3/lib/sprockets/base.rb:210:in `each_logical_path'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/static_compiler.rb:18:in`compile'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/assets.rake:52:in `internal_precompile'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/assets.rake:66:in`block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/assets.rake:56:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/assets.rake:19:in`invoke_or_reboot_rake_task'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.0/lib/sprockets/assets.rake:25:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in`load'
/usr/local/rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
Tasks: TOP => assets:precompile:primary

Any Help!, Thanks in advance

**Comment by mjonuschat** [comment]
I think you are using a different gem? `compass-twitter-bootstrap` if I am not mistaken?
In any case, blueprint is not and has never been a part of this gem.
