### ISSUE TITLE
bootstrap :File to import not found or unreadable

### ISSUE THREAD

**Issue by JeyKJey** [mjonuschat/bootstrap-sass-rails#34]
Hello!
I have found alredy some topics about my problem but I didnt understand how it should be fixed. Sorry =)

I was following http://ruby.railstutorial.org/chapters/filling-in-the-layout#fnref-5_5 tutorial and stuck by importing the bootstrap in app/assets/stylesheets/custom.css.scss.

That is my Gemfile:

source 'https://rubygems.org'
gem 'bootstrap-sass', '2.0.4'
gem 'rails', '3.2.8'

group :development, :test do
  gem 'sqlite3', '1.3.5'
  gem 'rspec-rails', '2.11.0'
end
# Gems used only for assets and not required
# in production environments by default.

group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end

gem 'jquery-rails', '2.0.2'

group :test do
  gem 'capybara', '1.1.2'
end

group :production do
  gem 'pg', '0.12.2'
end

And what error I get on localhost/sample_app/home

Sass::SyntaxError in Static_pages#home

Showing c:/Users/katja/Arbeit/rails_projects/sample_app/app/views/layouts/application.html.erb where line #5 raised:

File to import not found or unreadable: bootstrap.
Load path: Sass::Rails::Importer(c:/Users/katja/Arbeit/rails_projects/sample_app/app/assets/stylesheets/custom.css.scss)
  (in c:/Users/katja/Arbeit/rails_projects/sample_app/app/assets/stylesheets/custom.css.scss)
Extracted source (around line #5):

2: <html>
3:   <head>
4:     <title><%= full_title(yield(:title)) %></title>
5:     <%= stylesheet_link_tag    "application", media: "all" %>
6:     <%= javascript_include_tag "application" %>
7:     <%= csrf_meta_tags %>
8:     <!--[if lt IE 9]>
Rails.root: c:/Users/katja/Arbeit/rails_projects/sample_app

Application Trace | Framework Trace | Full Trace
app/assets/stylesheets/custom.css.scss:1
app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb__16020705_20168520'

Thank you in advanced

**Comment by mjonuschat** [comment]
Hi,

i guess I can only help with some basic ideas since you are using a different gem: [bootstrap-sass](https://github.com/thomas-mcdonald/bootstrap-sass)

First off I would try to put the bootstrap-sass gem into the :assets group so that it looks like this:

```
group :assets do
  gem 'sass-rails', '3.2.5'
  gem 'bootstrap-sass', '2.0.4'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end
```

I think that should already solve your problem. If it doesn't you might try putting the `@import "bootstrap";` directly into the application.css.scss, before you customize within custom.css.scss.

If none of these steps work you might give my gem a try by replacing `gem 'bootstrap-sass', '2.0.4'` with `gem 'bootstrap-sass-rails', '~> 2.0.4'` - maybe this will work better for you.

**Comment by JeyKJey** [comment]
Hey!
I have tried everything you suggested.
I dont have a file called application.css.scss, I have a application.css and by writing @import "bootstrap" in both files: custom.css.scss and application.css I changed nothing, I have no error but the page is without bootstrap itself. 

And then using your gem, should I type as well @import "bootstrap" in a custom.css.scss? If yes , then it doesnt work as well, I get the same error.

And what I found as well strange, when I write @import "bootstrap" in a cusom.css,scss it appears white, so the text edditor doesnt recognize the command and do not color it into pink/green as usual. Is it ok?

**Comment by mjonuschat** [comment]
That's really strange. Can you put your application up on github so I can have a look?

`@import "bootstrap";` will not work in a normal .css file - it has to be a .scss or .css.scss for it to work.

Wether your text-editor has syntax highlighting for SASS commands I can't really tell - if it knows SASS/SCSS it should highlight it.

**Comment by davoclavo** [comment]
It may be too late, but it may be useful for newcomers.

**Restart your server after doing a bundle install**
