### ISSUE TITLE
Transferring the file to be part of the project not part of gems

### ISSUE THREAD

**Issue by guyisra** [mjonuschat/bootstrap-sass-rails#35]
Is there a way to have the file of the gem be part of the project? and not be installed in the gems folder within ruby?

I know I can just copy the vendor/assets folder manually.. Are the other files needed?

**Comment by mjonuschat** [comment]
Hi,

there is a Sass helper function included in the gem that helps with some IE specific color formats that are needed in regard to the filters. You would need to integrate this into your project as well. Other than that the gem is mostly for easy packaging and using it in rails apps.
