### ISSUE TITLE
Variable arguments cause syntax error

### ISSUE THREAD

**Issue by mickmackk** [mjonuschat/bootstrap-sass-rails#36]
Hi,

I get the following syntax error when I use bootstrap-sass-rails in a simple configuration:

```
Invalid CSS after "...shadow($shadows": expected ")", was "...) {"
```

This is refering on a passage in the twitter/mixins file where variable arguments are use

```
// Drop shadows
@mixin box-shadow($shadows...) {
  -webkit-box-shadow: $shadows;
     -moz-box-shadow: $shadows;
          box-shadow: $shadows;
}
```

I am using:
- Ruby 1.9.2
- Rails 3.2.8
- sass 3.2.0
- sass-rails 3.2.5
- bootstrap-sass-rails 2.2.1

The gem file looks like this

```
group :assets do
  gem 'bootstrap-sass-rails'
end
```

The application.css.scss contains just a single line

```
@import 'twitter/bootstrap'
```

**Comment by mjonuschat** [comment]
Thats strange, the code is more or less the same as in the SASS docs. I can't reproduce the bug either and Travis says all tests are good on 1.9.2 either. I've uploaded a sample app that should be exactly as you described here:

https://github.com/yabawock/bootstrap-test

Could you try that and see if this works for you in your environment?

Thanks!

**Comment by mickmackk** [comment]
Thanks for your fast response. Both apps are running now (your test and my one). Unfortunately I was not able to identifiy the problem. But it must have been a local issue. I tried different versions of sass-rails and rails, uninstalled and installed them again and restarted the server serveral times. In between I got the following error message:

```
File to import not found or unreadable: twitter/bootstrapp.
```

But know it is running with this configuration:
- Ruby 1.9.2
- Rails 3.2.8
- sass 3.2.3 (-> different)
- sass-rails 3.2.5
- bootstrap-sass-rails 2.2.1

Sorry the unnecessary error report

**Comment by mjonuschat** [comment]
Ok, thanks for the feedback. I guess that last error message is due to a simple typo - „bootstrap“ is written with a single „p” at the end.

**Comment by zealot128** [comment]
had the same problem. Fixed it by updating sass-rails to latest stable.

**Comment by mjonuschat** [comment]
Guess I should bump the requirements on sass and sass-rails on the next release. There seems to be some kink in the variable arguments handing in the early 3.2.x releases...
