### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by tobidelius** [mjonuschat/bootstrap-sass-rails#37]
It would be awesome if you could update the gemspec file so we also can use it with Rails 4.

**Comment by mjonuschat** [comment]
I'll try getting the gem and test running under 4.0. If I get everything up and running i'll update the gemspec, no problem.

**Comment by mjonuschat** [comment]
Just a little update - got the testsuite running under 4.0 but the output generated by 4.0 is so different from 3.x that i'll have to find a new way to test the CSS results.

**Comment by mjonuschat** [comment]
I've committed Rails 4.0 support to the develop branch. If you bundle from that you should be good to go.

**Comment by tobidelius** [comment]
Awesome, thx!
