### ISSUE TITLE
Modal slide in

### ISSUE THREAD

**Issue by guyisra** [mjonuschat/bootstrap-sass-rails#38]
Could it be that the modal slide doesnt work properly?

my Modal just fades in and doesnt slide from the top

I see the html change from 
class="modal hide fade"

to

class="modal hide fade in"

so the javascript is happening.. its just that the slide doesn't

anyone have experienced this behavior?
could it be that something broke between versions?

**Comment by guyisra** [comment]
The transition seems to be fixed (or on the path to it..)
The first fade in is without slide. If I close it, it fades out with slide, and then if I open it again it works properly. It seems that the when the modal closes it fixes itself..

can you verify if it happens on your end or only on mine?

**Comment by mjonuschat** [comment]
Slides in just fine on the first invocation here. I've updated my test application here: https://github.com/yabawock/bootstrap-test

**Comment by guyisra** [comment]
oh sorry my bad. You are right - it works well.

I had a .in in the html leftover from my experiments trying to figure it out. thats why it didnt work on the first slide in

Thanks for the fix!
