### ISSUE TITLE
Dropdown secod level submenu not working

### ISSUE THREAD

**Issue by alaghu** [mjonuschat/bootstrap-sass-rails#40]
Hi there,
I am using bootstrap-sass-rails-2.2.1.2 with rails 3.2.8. I am unable to get the second level option working. I tried the exact same as http://jsfiddle.net/2Smgv/934/. But, the second level sub menu is not flying our (not working).

Thanks for your help.

<script src="https://gist.github.com/4137043.js?file=Second level submenu"></script>

https://raw.github.com/gist/4137043/d83f54f86413da7087dd2b54c80bf0e65adf25dd/Second%20level%20submenu

**Comment by mjonuschat** [comment]
Hi!

I can't reproduce this. The drop-downs in the fixed navbar as well as the pills work as designed. I've updated my test application with your code from jsfiddle: yabawock/bootstrap-test@dbbfe72413ee60ba016f3c00a09e92da0aec76e9

Please try if this works for you. Otherwise please fork the code and try if you could reproduce the error in the app, that would help finding the error easier.

**Comment by alaghu** [comment]
Hi Thanks for getting back to in a jiffy. I did deploy  your test https://github.com/yabawock/bootstrap-test repo. It does work. I have forked it for debugging. I think my issue might be the version I am using in my gem file. The version I am using is bootstrap-sass-rails-2.0.4.0 with rails 3.2.8. I will update the version and check.

Thanks for your prompt help.

**Comment by mjonuschat** [comment]
Second-Level Submenus have been introduced in Bootstrap 2.1 if i remember correctly.

**Comment by alaghu** [comment]
Thanks yabawock. I have now updated my bundle to   'bootstrap-sass-rails', '~> 2.2.1.0'. 

Sorry to bother you. I am puzzled with the following behaviour. 
1. Your test project once deployed locally : Submenu Works
2. My App referring the same code once deployed locally : Submenu Does Not Work
3. My App referring the same code once deployed to heroku : Submenu Works!

Additionally, in my local deployment of my app, even first level menu does not work

My Gemfile
https://gist.github.com/4154985

I hope you might know what I might be doing wrong. 

Thanks for your time.

**Comment by mjonuschat** [comment]
You might try to remove the following directories in your local app:
- tmp/cache
- tmp/sass-cache

This should remove all cached or compiled SCSS Fragments and force a regeneration of all assets even in dev environments

**Comment by alaghu** [comment]
Hi Yabawock,
You are the man. Thanks for the great tip. I went on to use <code>$ rake assets:clean </code>. Shut the server down and restarted, the drop down menu started working.

Thanks a bunch. Thanks for maintaining this gem!
