### ISSUE TITLE
incorporating the touchscreen fix

### ISSUE THREAD

**Issue by guyisra** [mjonuschat/bootstrap-sass-rails#41]
Is it possible to include the latest fix
https://github.com/twitter/bootstrap/commit/ed74992853054c57f33ef5d21941f0869e287552

**Comment by mjonuschat** [comment]
Bootstrap 2.2.2 is set to be released any day now (probably today) so it'll be included with the new release.

**Comment by mjonuschat** [comment]
Released gem version 2.2.2.0 which includes the fix.
