### ISSUE TITLE
README - Document proper way to add responsive styles

### ISSUE THREAD

**Issue by jacquescrocker** [mjonuschat/bootstrap-sass-rails#42]
Can't seem to understand from the docs. What's the proper way to include responsive styles? 

I can make send a README patch for it once I figure it out.

Thanks!

**Comment by mjonuschat** [comment]
Hi, there are several ways, depending on your application setup:

Using @import in an `.scss` file:

``` scss
@import 'twitter/bootstrap';
@import 'twitter/bootstrap/responsive';
```

Using =require (curtesy of Sprockets) to include the responsive partial  in your `.css` files:

``` css
/*
 *= require twitter/bootstrap
 *= require twitter/bootstrap/_responsive
 */
```

Or using =require in `.scss` files:

``` scss
#= require twitter/bootstrap
#= require twitter/bootstrap/_responsive
```

**Comment by jacquescrocker** [comment]
perfect, thanks a ton!
