### ISSUE TITLE
input-block-level styles are missing!

### ISSUE THREAD

**Issue by fgrehm** [mjonuschat/bootstrap-sass-rails#44]
I tried using the class but it is not working, I also [searched](https://github.com/search?l=&q=input-block-level++repo%3Ayabawock%2Fbootstrap-sass-rails&ref=advsearch&type=Code) the codebase but wasn't able to find it =/

For more information please refer to http://twitter.github.com/bootstrap/base-css.html and search for "Block level inputs"

Cheers

**Comment by mjonuschat** [comment]
Thanks for catching this - LESS seems to create a class for each mixin. I'll fix this shortly

**Comment by fgrehm** [comment]
Tks for fixing :-)
BTW, how do you guys keep up to date with bootstrap releases? I tried to find some kind of task or script on the repo but wasn't able to.

**Comment by mjonuschat** [comment]
Keeping up with the releases is a manual chore, there is no working converter for LESS to Sass or vice versa. So it's basically diff'ing the last two releases and porting what's needed. For the JS and Images this is easy, for the CSS it's a bit of work.

**Comment by fgrehm** [comment]
No worries!
I've been using this gem for a while now so I'll see if I can help with that in some way and contribute back :-)
