### ISSUE TITLE
Clearfix class not included?

### ISSUE THREAD

**Issue by DriesS** [mjonuschat/bootstrap-sass-rails#45]
Is there a reason why the clearfix css class of bootstrap is not included in this gem?

This is in the original css of bootstrap :

```
.clearfix {
   *zoom: 1;
}
.clearfix:before,
.clearfix:after {
   display: table;
   content: "";
   line-height: 0;
 }
.clearfix:after {
   clear: both;
}
```

**Comment by mjonuschat** [comment]
Probably because SCSS doesn't automatically creates a class for a mixin, which is different from LESS. I'll have a look and update as necessary

**Comment by DriesS** [comment]
Ok thank you. Will you roll-out the update/fix on previous versions also, as we use the  2.2.2.0 version of the gem/bootstrap?

**Comment by mjonuschat** [comment]
Hi, I've release a version 2.2.2.1 and 2.3.1.1 for the gem, both incorporating these fixes.

**Comment by swrobel** [comment]
AAAAAAAAAAGH Thanks, just spent a few hours debugging :sob:
