### ISSUE TITLE
Upgrade to 2.3.2

### ISSUE THREAD

**Issue by guyisra** [mjonuschat/bootstrap-sass-rails#48]
Hi

Sorry to bother for such a small thing, but bootstrap got updated to 2.3.2 to take care of the middle click in firefox not working

any chance of upgrading this gem as well?

thanks

**Comment by mjonuschat** [comment]
Hi,

I just pushed the update to 2.3.2 and released the 2.3.2.0 gem.

**Comment by guyisra** [comment]
Thanks a lot!
