### ISSUE TITLE
Compare to thomas-mcdonald/bootstrap-sass

### ISSUE THREAD

**Issue by exalted** [mjonuschat/bootstrap-sass-rails#49]
Hi,

how this repository is different from [thomas-mcdonald/bootstrap-sass](https://github.com/thomas-mcdonald/bootstrap-sass) please?

Thanks.

**Comment by mjonuschat** [comment]
Nowadays there isn't much of a difference anymore. When I started the gem the updates to bootstrap-sass were slow and bootstrap-sass wasn't namespaced, so it was easier to have conflicts when naming CSS files. AFAIK bootstrap-sass started to namespace the assets around the end of last year and the upstream updates are incorporated a bit faster, so I guess it's down to preference.

**Comment by exalted** [comment]
@yabawock thanks!
