### ISSUE TITLE
Bootstrap 3.0 offset naming inconsitency

### ISSUE THREAD

**Issue by jlaw90** [mjonuschat/bootstrap-sass-rails#57]
In bootstrap 3 to offset a column within a grid you'd use CSS class .col-lg-offset-\* whereas currently you have it as .col-offset-*.

While I understand this is easier as offsets are only allowed when the media is large enough for .col-lg-*, it is a potential cause for confusion for people new to the library and it could also break if twitter decide to add column offsets for smaller device resolutions in future.

**Comment by mjonuschat** [comment]
The 3.0.0.0rc1 gem is identical to the upstream rc1 version in regard to the naming of the columns. The development version gets updated every few days with the latest changes in upstream. As far as I can see the renaming/adding of the other offset classes has happened after the last merge, so they should show up in the develop branch with the next merge and be in 3.0.0.0rc2 when it's released upstream.

**Comment by mjonuschat** [comment]
Merged from upstream in 153dd214b343bc7cebb3abbf52901323cdf73e94
