### ISSUE TITLE
Using it with bootswatch-rails throws an invalid Undefined mixin 'border-radius' error

### ISSUE THREAD

**Issue by balaji-chronus** [mjonuschat/bootstrap-sass-rails#59]
ActionView::Template::Error (Undefined mixin 'border-radius'.

when i tried to import bootswatch styles template after importing the boostrap

**Comment by mjonuschat** [comment]
I've never tried it with bootswatch-rails. Could you show tell me which version of the gems you are usinge and please show the SCSS which throws the error.

**Comment by balaji-chronus** [comment]
Here is a snapshot of my assets group in my Gemfile
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass-rails'
gem 'bootswatch-rails'
gem "font-awesome-rails"

And here is the snapshot of my scss
// Using 'Amelia' bootswatch
@import "bootswatch/amelia/variables";

// Then bootstrap itself
@import "twitter/bootstrap";

// Bootstrap body padding for fixed navbar
body { padding-top: 60px; }

// And finally bootswatch style itself
@import "bootswatch/amelia/bootswatch";

@import "font-awesome";

/*
- This is a manifest file that'll automatically include all the stylesheets available in this directory
- and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
- the top of the compiled file, but it's generally better to create a new file per style scope.
  *= require_self
  
  *= require font-awesome
  
  *= require jquery.ui.core
  
  *= require jquery.ui.theme
  
  *= require_tree . 
  
  *= require select2

*/

hope this helps

**Comment by mjonuschat** [comment]
Ok, the problem is that you are using Bootstrap 3.0 with Bootswatch. Bootswatch currently needs Bootstrap 2.3, so you should lock bootstrap-sass-rails to the 2.3 version in the Gemfile. 

gem 'bootstrap-sass-rails', '~> 2.3'

Then the mixin should be availabe. Bootstrap 3.0 doesn't include the border-radius mixin anymore.

**Comment by balaji-chronus** [comment]
Thanks ! I think i need bootswatch-rails to work on bootstrap 3 then !
Thanks for the support ! much appreciated !
