### ISSUE TITLE
Bootstrap assets don't load when deployed on Heroku

### ISSUE THREAD

**Issue by danielristic** [mjonuschat/bootstrap-sass-rails#61]
During local development the gem works as expected showing bootstrap styles in the browser, but when deployed on Heroku, css and js are not loaded, showing errors like this in the logs:

```
ActionController::RoutingError (No route matches [GET] "/assets/application-d2158c36372a7dc329c38969f8791ca3.css")
```

**Comment by planas** [comment]
Doesn't look to be a problem with bootstrap. What version of Rails are you using? Are you precompiling your assets?

**Comment by danielristic** [comment]
I'm using Rails 4 and when I push to Heroku some point I have a 

```
Running: rake assets:precompile
Asset precompilation completed
```

Which I guess means that the assets precompilation is working as expected.

To be extra sure I ran `heroku run rake assets:precompile` manually after the deployment but I still have no bootstrap assets loading in production.

**Comment by planas** [comment]
That's pretty odd, but I still think it has nothing to do with bootstrap. Nonetheless, try to precompile your assets manually and then commit the changes before pushing to Heroku.

```
$ RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by joshhepworth** [comment]
@danielristic Are you using the [rails_12factor](https://github.com/heroku/rails_12factor) gem? Heroku published it for serving assets with Rails 4 on their platform because they can no longer inject plugins.

**Comment by danielristic** [comment]
@planas I tried it but still no assets showing in production.

@joshhepworth that did it! I saw the warning saying `Include 'rails_12factor' gem to enable all platform features` when deploying to heroku but the link to the documentation they provided was so unclear that I did not think it had anything to do with the assets pipeline. Thanks a lot!
