### ISSUE TITLE
How do I override the default variables?

### ISSUE THREAD

**Issue by ssrihari** [mjonuschat/bootstrap-sass-rails#64]
I am requiring "twitter/bootstrap" in application.css.
I'd like bootstrap to pick up my $font-family-sans-serif, instead of the one that comes with the gem. How do I do that?

**Comment by Spone** [comment]
Here is how I do it:

**app/assets/stylesheets/application.css.scss**

``` css
/*
 *= require_self
 */

@import "bootstrap_customizations";
@import "twitter/bootstrap.css.scss";
```

**app/assets/stylesheets/bootstrap_customizations.css.scss**

``` scss
/* Here you can assign variables that will be used instead of Bootstrap defaults */
$body-bg: #eee;
```

**Comment by mjonuschat** [comment]
That's exactly the way it needs to be done. If you use require the variables will be set in a different (closed) context for sprockets and you don't have access. If you use the Sass @import statement and set the variables before that, either by use of a custom scss file or by directly defining them in the application.css.scss it will work out just fine.

There's an example in the Wiki too: https://github.com/yabawock/bootstrap-sass-rails/wiki/How-To:-Customizing
