### ISSUE TITLE
Right tooltip not centered

### ISSUE THREAD

**Issue by pavolzbell** [mjonuschat/bootstrap-sass-rails#66]
Right tooltip not centered: is it possible to update this nice gem to fix this issue?

https://github.com/twbs/bootstrap/issues/9557

**Comment by mjonuschat** [comment]
Hi!

There is no fix that can be applied in the mentioned bug report - that issue only touches the bootstrap demo/documentation (which is not included in this gem). If you look at the file being modified it clearly states:

```
// NOTICE!! DO NOT USE ANY OF THIS JAVASCRIPT
// IT'S ALL JUST JUNK FOR OUR DOCS!
// ++++++++++++++++++++++++++++++++++++++++++
```

**Comment by pavolzbell** [comment]
sorry, my mistake
