### ISSUE TITLE
Not actual wiki documentation

### ISSUE THREAD

**Issue by romikoops** [mjonuschat/bootstrap-sass-rails#67]
Hi there, just tried to use your last gem version, and put code as described here https://github.com/yabawock/bootstrap-sass-rails/wiki/How-To:-Enable-responsive-features

As result, I had 

<pre>
ActionView::Template::Error (couldn't find file 'twitter/bootstrap/_responsive'
</pre>

After quick investigation I realized you have wiki pages for version 2.x. Please specify fix it, because I guess other guys will have the same issue

**Comment by mjonuschat** [comment]
I renamed the page to make it clearer that it applies to Bootstrap 2.x only. Bootstrap 3 is responsive by default.
