### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by khashabawy** [mjonuschat/bootstrap-sass-rails#69]
3.1 released and still no RTL ? why not ?

foundation 5 and other frameworks are RTLing and you r not !!!

**Comment by mjonuschat** [comment]
Sorry, I am not one of the authors of Twitter Bootstrap, I only maintained a port to Sass. The Sass port always was a close to the upstream less version as possible. Starting with Version 3.1 Bootstrap has an official Sass port so I don't even do the conversion myself anymore. This gem is only a shim that changes the namespace nowadays which I will maintain until Bootstrap 4 or the end of 2014, whichever comes first. 

Regarding the support of RTL you want to address your concerns/wishes at the „master“ project at https://github.com/twbs/bootstrap
